<?php 
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
$app->before(function (Request $request) {
    if (0 === strpos($request->headers->get('Content-Type'), 'application/json')) {
        $data = json_decode($request->getContent(), true);
        $request->request->replace(is_array($data) ? $data : array());
    }
});





/***
 * Load files from form
 */
$app->post('/load',function(Request $request) use($app)
{

    $file = $request->files->get('file');
    if ($file !== null) {
 
      //the name
        $nameOfFile = $file->getClientOriginalName();
      
      /***
       *  to get infos from the name
      */
      
        $category = substr($nameOfFile,0,2);
        $numOfTest= substr($nameOfFile,2,3);
        $numOfQuestion = substr($nameOfFile,5,2);
        $answers = substr($nameOfFile,7,1);
        $correctAsnwer = substr($nameOfFile,8,1);
        

        $response = "category:".$category." / numOfTest : ".$numOfTest." / numOfQuestion : ".$numOfQuestion." / answers: ".$answers." / correctAsnwer : ".$correctAsnwer;
 
      // insertion inside your database 
      
       
        
        $path = 'images/';
        $file->move($path, $file->getClientOriginalName());
        
        $app['db']->insert('maindb', array('Category'=>$category,'Num_Test'=>$numOfTest,'Num_Question'=>$numOfQuestion,'Quanity_Ans'=> $answers,'Num_Correct_Ans'=>$correctAsnwer));
        
        
        
        return new Response($response); 
    } else {
        return new Response("An error ocurred. Did you really send a file?");
    }
    
});


 /***
  * get all categories : test
  */
  
$app->get('/category',function() use($app)
{
    $sql = 'select Category, Num_Test from maindb';
return $app->json($app['db']->fetchAll($sql));
});



/***
 * Script to read files from folders
 * then put into db
 */
$app->get('/script/PutFilesIntoDb',function() use($app)
{
  $path= './images';
  $dir = dir($path);
  
  $response = "";
  
  //array of files
  $filesNames = [];
  while($name = $dir->read())
  {
    $filesNames[] = $name;
  }
  
  foreach($filesNames as $name)
  {
    //we take all file with a name bigger than 3 characters
    if(strlen($name)>3)
    {
      
      //rest
      $response = $response.''.stringToDBformat($name).'<br/>';
      // save in db 
      
     // saveInDb($name,$app);
     
      
    }
      
      
      
  }
  
  return new Response($response);
   
});

/** view looking
 * */
 
 $app->get('/tests/twig/index',function() use($app)
{
  $categories = $app['dao.quizz']->findAll();
  return $app['twig']->render('index.html.twig', array('categories' => $categories));
});



//functions to make life easier 
function saveInDb($nameOfFile,$app)
{
    $category = substr($nameOfFile,0,2);
        $numOfTest= substr($nameOfFile,2,3);
        $numOfQuestion = substr($nameOfFile,5,2);
        $answers = substr($nameOfFile,7,1);
        $correctAsnwer = substr($nameOfFile,8,1);
        
    $app['db']->insert('maindb', array('Category'=>$category,'Num_Test'=>$numOfTest,'Num_Question'=>$numOfQuestion,'Quanity_Ans'=> $answers,'Num_Correct_Ans'=>$correctAsnwer));
        
        
        
}
function stringToDBformat($nameOfFile)
{
   $category = substr($nameOfFile,0,2);
        $numOfTest= substr($nameOfFile,2,3);
        $numOfQuestion = substr($nameOfFile,5,2);
        $answers = substr($nameOfFile,7,1);
        $correctAsnwer = substr($nameOfFile,8,1);
        
        return "category:".$category." / numOfTest : ".$numOfTest." / numOfQuestion : ".$numOfQuestion." / answers: ".$answers." / correctAsnwer : ".$correctAsnwer;
 
}

/*2))) index page

A1
Test1 test2
B
Test1 test1



3) then questions generated by pic

a1
test1 test2 

// 1 by page
//~~~ cookies

1 ) ### script to load files into db
*/


//-login :  student /
//